services:
    mariadb:
        image: mariadb:11.5
        container_name: mariadb-dolibarr
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        ports:
            - 54001:3306
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./system/mariadb_data:/var/lib/mysql
        networks:
            - dolibarr
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3        

    web:
        image: dolibarr/dolibarr:19
        container_name: dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
            DOLI_ADMIN_LOGIN: admin
            DOLI_ADMIN_PASSWORD: admin
            PHP_INI_DATE_TIMEZONE: Europe/Berlin
        ports:
            - "54000:80"
        volumes:
            - ./system/dolibarr_data:/var/www/documents
            - ./system/dolibarr_custom:/var/www/html/custom
        networks:
            - dolibarr
        restart: always
        depends_on:
          - mariadb
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 10s
            retries: 3

    phpmyadmin:
        image: phpmyadmin:5.2.1
        container_name: phpmyadmin-dolibarr
        restart: always
        ports:
          - 54002:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_PORT=3306
          - PMA_USER=phpmyadmin
          - PMA_PASSWORD=phpmyadmin
          - PMA_HOST=mariadb
        networks:
          - dolibarr
        depends_on:
          - mariadb
        healthcheck:
          test: ["CMD", "curl", "-f", "http://mariadb:3306"]
          interval: 30s
          timeout: 10s
          retries: 10

    metabase:
      image: metabase/metabase:v0.50.23
      container_name: metabase-dolibarr
      hostname: metabase
      volumes: 
        - ./system/metabase:/dev/random:ro
      ports:
        - 54003:3000
      environment:
        MB_DB_TYPE: mysql
        MB_DB_DBNAME: metabase
        MB_DB_PORT: 3306
        MB_DB_USER: metabase
        MB_DB_PASS: metabase
        MB_DB_HOST: mariadb
      depends_on:
        - mariadb
      networks:
        - dolibarr
      restart: always
      healthcheck:
        test: curl --fail -I http://localhost:3000/api/health || exit 1
        interval: 15s
        timeout: 5s
        retries: 5
        
networks:
    dolibarr:
